import { GPT } from "@/components/GPT"
import { Header } from "@/components/Header"
import { Inter } from "next/font/google"
import Head from "next/head"

const inter = Inter({ subsets: ["latin"] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Nhestrompia</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://rsms.me/" />
        <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
      </Head>
      <main className="overflow-scroll snap-y ... snap-mandatory">
        <Header />
        <GPT />
      </main>
    </>
  )
}
