export const projects = [
  {
    id: 1,
    title: "Binge Time",
    overview: "Project 1 content goes here",
    lesson: "lorem20asdasd  asda sdas dasd asdasddddddd gfsg fs asd s",
    tech: ["react", "next-js", "tailwind", "chatgpt"],
    image: "binge",
    links: ["", ""],
  },
  {
    id: 2,
    title: "Blackjack Time",
    overview: "Project 1 content goes here",
    lesson: "lorem20asdasd  asda sdas dasd asdasddddddd gfsg fs asd s",
    tech: [
      "react",
      "next-js",
      "tailwind",
      "nodejs",
      "socketio",
      "solidity",
      "ethers",
      "hardhat",
    ],
    image: "binge",
    links: ["", ""],
  },
  {
    id: 3,
    title: "Fautor Time",
    overview: "Project 1 content goes here",
    lesson: "lorem20asdasd  asda sdas dasd asdasddddddd gfsg fs asd s",
    tech: [
      "react",
      "next-js",
      "tailwind",
      "mongodb",
      "solidity",
      "ethers",
      "hardhat",
    ],
    image: "binge",
    links: ["", ""],
  },
  ,
]
